/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerHistoryRouteImport } from './routes/officer.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerHistoryRoute = OfficerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OfficerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/officer': typeof OfficerRouteWithChildren
  '/verify': typeof VerifyRoute
  '/officer/history': typeof OfficerHistoryRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/verify': typeof VerifyRoute
  '/officer/history': typeof OfficerHistoryRoute
  '/officer': typeof OfficerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/officer': typeof OfficerRouteWithChildren
  '/verify': typeof VerifyRoute
  '/officer/history': typeof OfficerHistoryRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/officer' | '/verify' | '/officer/history' | '/officer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/verify' | '/officer/history' | '/officer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/officer'
    | '/verify'
    | '/officer/history'
    | '/officer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  OfficerRoute: typeof OfficerRouteWithChildren
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/history': {
      id: '/officer/history'
      path: '/history'
      fullPath: '/officer/history'
      preLoaderRoute: typeof OfficerHistoryRouteImport
      parentRoute: typeof OfficerRoute
    }
  }
}

interface OfficerRouteChildren {
  OfficerHistoryRoute: typeof OfficerHistoryRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerHistoryRoute: OfficerHistoryRoute,
  OfficerIndexRoute: OfficerIndexRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  OfficerRoute: OfficerRouteWithChildren,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
